version: 1.0.{build}

image: Visual Studio 2019

environment:
  MAVEN_HOME: C:\maven\apache-maven-3.3.9
  JAVA_HOME: C:\Program Files\Java\jdk11
  PATH: C:\maven\apache-maven-3.3.9\bin;C:\Program Files\Java\jdk11\bin;$(PATH)
  MAVEN_OPTS: -Xmx4g
  JAVA_OPTS: -Xmx4g
  M2: $(USERPROFILE)\.m2

  secret:
    secure: zNgjsN45sSA5kGW/jo7TJA==

install:

  # Install Maven if not present
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'https://dlcdn.apache.org/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.zip',
          'C:\maven-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")

      }

  - ps: |
      Write-Host validation
      $env:secret -eq "test_keyphrase"
      Write-Host `$env:secret is $env:secret

  - \%JAVA_HOME%\bin\java -version

# log4jna depends on JNA 4.x, so we must set jna.nosys=true to avoid java.lang.UnsatisfiedLinkError
# https://github.com/java-native-access/jna/issues/384
build_script:
  - mvn -B -Djna.nosys=true clean install 

# Maven run the tests as part of the build we do not need to run them again
test: off

cache:
  # Cache Maven and m.2
  - '%MAVEN_HOME%'
  - '%M2%'
