version: 1.0.{build}

image: Visual Studio 2019

environment:
  MAVEN_HOME: C:\maven\apache-maven-3.3.9
  JAVA_HOME: C:\Program Files\Java\jdk11
  PATH: C:\maven\apache-maven-3.3.9\bin;C:\Program Files\Java\jdk11\bin;$(PATH)
  MAVEN_OPTS: -Xmx4g
  JAVA_OPTS: -Xmx4g
  M2: $(USERPROFILE)\.m2
  SECURE_FILE_DIR: C:\appveyor-tools
  SECURE_FILE_CMD: C:\appveyor-tools\secure-file.exe
  SECURE_FILE_DEC: '-decrypt'
  SECURE_FILE_SEC: '-secret'
  SECURE_FILE_SLT: '-salt'
  TEST_ENC: $(APPVEYOR_BUILD_FOLDER)\test.md.enc

  # Keyphrase for secure-file.exe
  secret:
    secure: zNgjsN45sSA5kGW/jo7TJA==
  salt:
    secure: 1NA4tAkyzsiZxCzZs398+YMNtVs1KARX9saQd0Kuk7vj9Myklo3bk0dpE2sY6M+IbBBlv4+svPMKPXeXExXeBA==

install:

  # Install Maven if not present
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'https://dlcdn.apache.org/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.zip',
          'C:\maven-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")

      }

  # Test decode
  - ps: |
      Write-Host `$env:secret is $env:secret

  # Test Command from Env
  - | 
      "%SECURE_FILE_CMD%"

  # Install secure-file if not present
  - ps: |
     if (!(Test-Path -Path $env:SECURE_FILE_DIR )) {
        cd C:\
        iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
        cd $env:APPVEYOR_BUILD_FOLDER
     }

  # Test decode
  - ps: |
      & $env:SECURE_FILE_CMD $env:SECURE_FILE_DEC $env:TEST_ENC $env:SECURE_FILE_SEC $env:secret $env:SECURE_FILE_SLT $env:salt
      cat .\test.md

# log4jna depends on JNA 4.x, so we must set jna.nosys=true to avoid java.lang.UnsatisfiedLinkError
# https://github.com/java-native-access/jna/issues/384
build_script:
  - mvn -B -Djna.nosys=true clean install 

# Maven run the tests as part of the build we do not need to run them again
test: off

cache:
  # Cache Maven and m.2
  - '%MAVEN_HOME%'
  - '%M2%'
